# Generated by Django 2.0.1 on 2018-07-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180715_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothe',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
