# Generated by Django 2.0.1 on 2018-07-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180715_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothe',
            name='feedbacks',
        ),
        migrations.RemoveField(
            model_name='electronic',
            name='feedbacks',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='feedbacks',
        ),
    ]
