# Generated by Django 2.0.1 on 2018-07-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180715_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothe',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='clothe/'),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='electronic/'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='furniture/'),
        ),
    ]
