# Generated by Django 2.1.7 on 2019-04-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190424_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ER', 'Electronics'), ('CL', 'Clothes'), ('FR', 'Furniture')], max_length=2, null=True),
        ),
    ]
