# Generated by Django 2.1.7 on 2019-06-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
        migrations.AddField(
            model_name='cart',
            name='totalval',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
