# Generated by Django 2.0.1 on 2018-07-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('mobile_no', models.IntegerField(max_length=10)),
            ],
        ),
    ]
