# Generated by Django 2.0.1 on 2018-07-16 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180715_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='lname',
        ),
    ]
